server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: 'https://github.com/gabewallace/mindrepo.git'
          searchPaths: "backend/config/"
          default-label: 'dev'
